---

- name: Install nginx
  apt: name=nginx-light state=present

- name: Remove nginx default site configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Install proper nginx configuration
  template: src=dnevnik.conf.j2 dest=/etc/nginx/sites-enabled/{{ engine.name }}.conf
  notify: reload nginx

# TODO Add proper expires: max to static files

- name: Add nginx user to the {{ engine.name }} group
  user: name=www-data groups={{ engine.name }} append=yes
  notify: restart nginx