---
- name: Install php-fpm and required modules and tools
  apt: name={{ item }} state=present
  with_items:
    - php-fpm
    - php-gd
    - php-curl
    - php-apcu
  notify: restart php-fpm

- name: Remove defaul php-fpm pool
  file: name=/etc/php/7.2/fpm/pool.d/www.conf state=absent
  notify: restart php-fpm

- name: Create php-fpm logfile for {{ engine.name }}
  file: name=/var/log/php-fpm.{{ engine.name }}.log owner={{ engine.name }} state=touch
  changed_when: False # Never report as changed

- name: Create php-fpm pool for our engine
  template: src=dnevnik.conf.j2 dest=/etc/php/7.2/fpm/pool.d/{{ engine.name }}.conf
  notify: restart php-fpm

# TODO Optimize the php-fpm config for production performance
