---
- name: Install php5-fpm and required modules and tools
  apt: name={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-gd
    - php5-curl
    - php5-imagick
    - php5-xcache
  notify: restart php-fpm

- name: Remove defaul php-fpm pool
  file: name=/etc/php5/fpm/pool.d/www.conf state=absent
  notify: restart php-fpm

- name: Create php-fpm logfile for dnevnik
  file: name=/var/log/fpm-php.dnevnik.log owner=dnevnik state=touch

- name: Create php-fpm pool for our engine
  copy: src=dnevnik.conf dest=/etc/php5/fpm/pool.d/dnevnik.conf
  notify: restart php-fpm

# TODO Setup proper logging in php-fpm config
