---
- name: Install php5-fpm
  apt: name=php5-fpm state=present

- name: Install php5-mysqlnd
  apt: name=php5-mysqlnd state=present

- name: Remove defaul php-fpm pool
  file: name=/etc/php5/fpm/pool.d/www.conf state=absent

- name: Create php-fpm pool for our engine
  copy: src=dnevnik.conf dest=/etc/php5/fpm/pool.d/dnevnik.conf
  notify: restart php-fpm

# TODO Setup proper logging in php-fpm config
