---
install_from: http://lleo.me/dnevnik
engine:
  name: dnevnik
  hostname: lleo.pimenov.cc
  subdir: ""

  admin:
    name: Kirill
    email: kirushik@example.com
    password: BeanBagLaterSkyJigsawNode
mysql:
  root_password: KAHxn(sdFXASh=x1
  database: dnevnik
mail:
  server: smtp.yandex.ru
  port: 465
  username: psychopomp@yandex.ru
  password: 12345