---
install_from: https://lleo.me/dnevnik
engine:
  name: dnevnik
  hostname: local.dev
  subdir: "" # Not working as expected at the moment

  admin:
    name: lleo
    email: lleo@lleo.me
    password: FinForest
mysql:
  root_password: KuRarrE7
  database: dnevnik
