---
- name: Load MariaDB package signing key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
- name: Plug in MariaDB repo (Canadian mirror)
  apt_repository: repo='deb http://mariadb.mirror.iweb.com//repo/10.0/ubuntu {{ ansible_distribution_release }} main' state=present

- name: Set MariaDB root password for installation
  debconf: name=mysql-server-10.0 question='mysql-server/root_password' value={{ mysql_root_password }} vtype=password
  changed_when: False # Never report as changed
- name: Set MariaDB root password confirmation
  debconf: name=mysql-server-10.0 question='mysql-server/root_password_again' value={{ mysql_root_password }} vtype=password
  changed_when: False # Never report as changed

- name: Install the MariaDB server
  apt: name=mariadb-server state=present
- name: Start MariaDB server (and enable its autostart)  
  service: name=mysql state=started enabled=yes
