---
- name: Add NewRelic repo signing key to trusted keychain
  apt_key: id=0x548C16BF url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Plug in NewRelic repo
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: Set NewRelic application name
  debconf: name=newrelic-php5 question=newrelic-php5/application-name value='{{ newrelic.application_name }}' vtype=string
- name: Set NewRelic license key
  debconf: name=newrelic-php5 question=newrelic-php5/license-key value='{{ newrelic.license_key }}' vtype=string

- name: Install NewRelic PHP monitoring agent
  apt: update_cache=yes name=newrelic-php5 state=present
  notify:
    - restart php-fpm
    - restart nginx

- name: Install NewRelic system monitoring agent
  apt: name=newrelic-sysmond state=present

- name: Setup NewRelic system monitor
  command: /usr/sbin/nrsysmond-config --set license_key='{{ newrelic.license_key }}'

- name: Enable NewRelic system monitor autostart
  service: name=newrelic-sysmond state=started enabled=yes
