---
- name: Create folder for lleo engine, with gid set
  file: path=/var/www/{{ engine.name }} owner={{ engine.name }} group={{ engine.name }} state=directory mode=2770

- name: Fetch lleo's installer to /tmp
  get_url: url={{ install_from }}/minimum.zip dest=/tmp/minimum.zip force=yes

- name: Install zip unarchiver
  apt: name=unzip state=present

- name: Extract installer components into /var/www/{{ engine.name }}
  unarchive: src=/tmp/minimum.zip dest=/var/www/{{ engine.name }} copy=no creates=/var/www/{{ engine.name }}/site_module/INSTALL.php

- name: Check if config.php is already there
  stat: path=/var/www/{{ engine.name }}/config.php
  register: config_present

- name: Install apg password generation tool
  apt: name=apg state=present

- name: Generate random salt for config
  # We shouldn't allow quotes symbols and escaping slashes
  command: apg -a 1 -m 128 -E \\\'\" -n 1
  register: random_salt
  when: not config_present.stat.exists

- name: Setting up config.php
  template: src=config.php.j2 dest=/var/www/{{ engine.name }}/config.php owner={{ engine.name }} group={{ engine.name }} mode=664
  when: not config_present.stat.exists

- name: Ensure correct permissions on /var/www/{{ engine.name }}
  file: path=/var/www/{{ engine.name }} owner={{ engine.name }} group={{ engine.name }} recurse=yes