---
- name: Create folder for lleo engine, with gid set
  file: path=/var/www/dnevnik owner=dnevnik group=dnevnik state=directory mode=2770

- name: Fetch lleo's installer to /tmp
  get_url: url={{ install_from }}/dnevnik/minimum.zip dest=/tmp

- name: Install zip unarchiver
  apt: name=unzip state=present

- name: Extract installer components into /var/www/dnevnik
  unarchive: src=/tmp/minimum.zip dest=/var/www/dnevnik copy=no

- name: Setting up config.php
  template: src=config.php.j2 dest=/var/www/dnevnik/config.php owner=dnevnik group=dnevnik mode=664

- name: Ensure correct permissions on /var/www/dnevnik
  file: path=/var/www/dnevnik owner=dnevnik group=dnevnik recurse=yes

# TODO сделать папку disable и запретить нгинксу доступ туда