---
- name: Install ufw firewall
  apt: name=ufw state=present

- name: Open desired ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 22
    - 80

- name: Turn ufw on
  ufw: state=enabled

- name: Add current user to ssh group to allow ssh access with new config
  user: name={{ansible_env.SUDO_USER}} groups=ssh append=yes

- name: Overwrite sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh daemon

- name: Create user for lleo engine
  user: name=dnevnik shell=/dev/null system=yes

- name: Add current sudoer to the dnevnik group
  user: name={{ansible_env.SUDO_USER}} groups=dnevnik append=yes

- name: Create hidden folder for engine internals
  file: path=/var/www/dnevnik/hidden owner=dnevnik state=directory

- name: Create hidden subfolder for uploads
  file: path=/var/www/dnevnik/hidden/uploads owner=dnevnik state=directory
