---
- name: Install ufw firewall
  apt: name=ufw state=present

- name: Open desired ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 22
    - 80

- name: Turn ufw on
  ufw: state=enabled

- name: Restrict ssh access to current user only
  user: name={{ansible_env.SUDO_USER}} groups=ssh append=yes

- name: Overwrite sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh daemon

- name: Create users for each engine instance
  user: name={{item.key}}_user shell=/dev/null system=yes
  with_dict: engines

- name: Add current sudoer to all those user's groups
  user: name={{ansible_env.SUDO_USER}} groups={{item.key}}_user append=yes
  with_dict: engines

- name: User setgid on all engine folders
  file: name=~{{item.key}}_user mode=2770
  with_dict: engines
