---
- name: Install ufw firewall
  apt: name=ufw state=present

- name: Open desired ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 22
    - 80

- name: Turn ufw on
  ufw: state=enabled

- name: Add current user to ssh group to allow ssh access with new config
  user: name={{ansible_env.SUDO_USER}} groups=ssh append=yes

- name: Overwrite sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh daemon

- name: Create user for lleo engine
  user: name=dnevnik shell=/dev/null system=yes

- name: Add current sudoer to www-data group
  user: name={{ansible_env.SUDO_USER}} groups=www-data append=yes

- name: Create folder for lleo engine
  file: path=/var/www/dnevnik owner=dnevnik group=www-data state=directory mode=2770

- name: User setgid on engine folder
  file: name=/var/www/dnevnik mode=2770