---
- name: Install ufw firewall
  apt: name=ufw state=present

- name: Open desired ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 22
    - 80

- name: Turn ufw on
  ufw: state=enabled

- name: Add current user to ssh group to allow ssh access with new config
  user: name={{ansible_env.SUDO_USER}} groups=ssh append=yes

- name: Overwrite sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
    - restart ssh daemon
  when: vagrant is not defined

- name: Create user for lleo engine
  user: name={{ engine.name }} shell=/dev/null system=yes

- name: Add current sudoer to the {{ engine.name }} group
  user: name={{ansible_env.SUDO_USER}} groups={{ engine.name }} append=yes

- name: Create hidden folder for engine internals
  file: path=/var/www/{{ engine.name }}/hidden owner={{ engine.name }} state=directory

- name: Create hidden subfolder for uploads
  file: path=/var/www/{{ engine.name }}/hidden/uploads owner={{ engine.name }} state=directory
