---
- name: Install memcached and it's php driver
  apt: name={{item}} state=present
  with_items:
    - memcached
    - php5-memcache

- name: Enable memcached service on startup
  service: name=memcached state=started enabled=yes
