---
- name: Install memcached and it's php driver
  apt: name=memcached state=present
  with_items:
    - memcached
    - php5-memcached

- name: Enable memcached service on startup
  service: name=memcached state=started enabled=yes
