- name: Install latest python 2.7 repo
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'

- name: Update apt packages if needed
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe

- name: Install unattended-upgrades tools
  apt: pkg=unattended-upgrades state=present

- name: Set up periodic package fetching
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=0644

- name: Set up unattended packages upgrade
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644
